### ISSUE TITLE
`atomistics.BulkStructure` to `atomistics.bulk_structure`?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_contrib#673]
https://github.com/pyiron/pyiron_contrib/blob/b6a1fb33385fcb1c87e41b69477b7038ef07ff8c/pyiron_contrib/workflow/workflow.py#L121

I presume it has to be called `atomistics.bulk_structure`?

**Comment by liamhuber** [comment]
> https://github.com/pyiron/pyiron_contrib/blob/b6a1fb33385fcb1c87e41b69477b7038ef07ff8c/pyiron_contrib/workflow/workflow.py#L121
> 
> I presume it has to be called `atomistics.bulk_structure`?

No, it runs fine. Cf. the workflow notebook, which uses the exact same syntax and is included and passing in the test suite.

The issue is that node package manager sets its attributes [based on the class name](https://github.com/pyiron/pyiron_contrib/blob/b6a1fb33385fcb1c87e41b69477b7038ef07ff8c/pyiron_contrib/workflow/node_library/package.py#L27), which are converted to CamelCase from the node function names [in the decorator](https://github.com/pyiron/pyiron_contrib/blob/b6a1fb33385fcb1c87e41b69477b7038ef07ff8c/pyiron_contrib/workflow/node.py#L652).

I'm not saying that it _has_ to be this way; I think the node package will basically only have access to the class name so we're stuck there, but there's no reason that the decorator needs to CamelCase the class names -- we could just directly use function name.

The catch is that you either wind up with

```python
@node("output")
def CamelCaseFunctionBecauseItWillBeAClass(x):
    return x

my_node = CamelCaseFunctionBecauseItWillBeAClass(x=1)
```

OR

```python
@node("output")
def this_will_not_look_like_a_class_instantiation(x):
    return x

my_node = this_will_not_look_like_a_class_instantiation(x=1)
```

As far as I can tell, this is just a fundamental sad thing about using the decorator to convert a class to a function. We have some freedom to change what we assign as the class name, and thus what it looks like when we access it from a `NodePackage`, but the underlying sadness is still there.
